### ISSUE TITLE
notifier service hangs on empty slack 'webhook_url'

### ISSUE THREAD

**Issue by arbeit** [GoogleCloudPlatform/forseti-security#1275]
Found in `2.0-dev`. When the notifier config looks like this

```yaml
    - name: slack_webhook_pipeline
      configuration:
        webhook_url: ''
```
and the notifier is run it gets hung up and never terminates:

```
$ forseti --endpoint [::]:50051 notifier run
Retrieved 43 violations for resource 'policy_violations'
Running 'email_violations_pipeline' for resource 'policy_violations'
Running 'gcs_violations_pipeline' for resource 'policy_violations'
Running 'slack_webhook_pipeline' for resource 'policy_violations'
```

**Comment by arbeit** [comment]
I removed the slack pipeline; now the notifier hangs on the `gcs_violations_pipeline` -- it might be the actual culprit

**Comment by arbeit** [comment]
The `email_violations_pipeline` is successful -- I do receive the email

**Comment by arbeit** [comment]
I have 2 email pipelines now and the notifier hangs; I guess the pipeline type does not matter -- if there's more than one pipeline it makes the notifier hang.
The second `email_violations_pipeline` does manage to send out the email though.

**Comment by arbeit** [comment]
I just looked at the GCS bucket used by the `gcs_violations_pipeline` and see that json files with violation data were uploaded.

**Comment by joecheuk** [comment]
This issue is resolved in #1279 , @arbeit feel free to re-open if you see the same error again.

**Comment by arbeit** [comment]
This is not fully fixed yet. If there is no `findings` stanza in the yaml config file, the server will run into the following exception

    > /home/altair/virtenvs/fsec/lib/python2.7/site-packages/forseti_security-2.0.0-py2.7.egg/google/cloud/forseti/notifier/notifier.py(197)run()->None
    -> if notifier_configs.get('violation').get('findings').get('enabled'):
    (Pdb) 
    AttributeError: "'NoneType' object has no attribute 'get'"

and hang due to https://github.com/GoogleCloudPlatform/forseti-security/blob/2.0-dev/google/cloud/forseti/notifier/notifier.py#L196
